language: php

php:
  - 5.5

before_script: composer install -n

script: phpunit -c app

branches:
  only:
    - master
    - develop

deploy:
  provider: heroku
  api_key:
    secure: bJH959wQ5mckutG6deDLdOMe4MkDks6NtOBxVKdhaglLyFepSKD1n3DkAZiX1xdPWAfFkORZWgRSFifjJGdEPFa1U7Ds0X4LiO8OziEhlaaoAF3rhG0OF9E04TxF7s20O735ExMrXa7L0N/YVgsvNgYjCrNtNahXwBeoI/urh+M=
  app:
    #master: heroku-symfony2-test0515
    develop: heroku-symfony2-test0515
