imports:
    - { resource: config.yml }
    - { resource: parameters_heroku.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_heroku.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
    session:
       handler_id: session.handler.memcached

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  "php://stderr"
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com

services:
    session.memcached:
        class: Memcached
        calls:
            - [ addServer, [ %session_memcached_host%, %session_memcached_port% ]]

    session.handler.memcached:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: [ @session.memcached, { prefix: %session_memcached_prefix%, expiretime: %session_memcached_expire% }]
