parameters:
    database_driver: pdo_mysql
    database_host: us-cdbr-east-06.cleardb.net
    database_port: 3306
    database_name: heroku_7c81c847e79ca9f
    database_user: b8ebae2c36ab48
    database_password: bfcefadd
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: ja
    secret: ThisTokenIsNotSoSecretChangeIt

    session_memcached_host: localhost
    session_memcached_port: 11211
    session_memcached_prefix: heroku
    session_memcached_expire: 3600
